# Generated by Django 3.2.7 on 2021-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usertransactionhistory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('REFUND', 'Refund'), ('TAKEBACK', 'Takeback')], max_length=255),
        ),
    ]
