# Generated by Django 3.2.7 on 2021-11-12 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertransactionhistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConstant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('tnbc_account_number', models.CharField(default='xyz', max_length=255)),
                ('check_tnbc_confirmation', models.BooleanField(default=False)),
                ('tnbc_bank_ip', models.CharField(default='xyz', max_length=255)),
                ('bot_manager_id', models.BigIntegerField(default=0)),
                ('offer_channel_id', models.BigIntegerField(default=0)),
                ('dispute_channel_id', models.BigIntegerField(default=0)),
                ('agent_role_id', models.BigIntegerField(default=0)),
                ('admin_role_id', models.BigIntegerField(default=0)),
                ('minimum_advertisement_amount', models.BigIntegerField(default=0)),
                ('maximum_advertisement_amount', models.BigIntegerField(default=0)),
                ('minimum_escrow_amount', models.BigIntegerField(default=0)),
                ('maximum_escrow_amount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
    ]
