# Generated by Django 3.2.7 on 2021-11-13 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211112_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='BotConstant',
        ),
    ]
