# Generated by Django 3.2.6 on 2021-08-29 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField()),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tnbc', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_status', models.CharField(choices=[('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('CONFIRMED', 'Confirmed')], max_length=255)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('IDENTIFIED', 'Identified'), ('UNIDENTIFIED', 'Unidentified'), ('REFUNDED', 'Refunded')], max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('signature', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
                ('total_confirmations', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_id', models.IntegerField(unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=255, unique=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=255)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escrow.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escrow.user')),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute'), ('ADMIN_SETTLED', 'Admin Settled'), ('ADMIN_CANCELLED', 'Admin Cancelled')], max_length=255)),
                ('initiator_cancelled', models.BooleanField(default=False)),
                ('successor_cancelled', models.BooleanField(default=False)),
                ('settled_towards', models.CharField(choices=[('INITIATOR', 'Initiator'), ('SUCCESSOR', 'Successor')], default='SUCCESSOR', max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='escrow.user')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiator', to='escrow.user')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='successor', to='escrow.user')),
            ],
        ),
    ]
