# Generated by Django 3.2.6 on 2021-09-04 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tnbc_escrowed', models.IntegerField(default=0)),
                ('total_escrows', models.IntegerField(default=0)),
                ('total_disputes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute'), ('ADMIN_SETTLED', 'Admin Settled'), ('ADMIN_CANCELLED', 'Admin Cancelled')], max_length=255)),
                ('initiator_cancelled', models.BooleanField(default=False)),
                ('successor_cancelled', models.BooleanField(default=False)),
                ('settled_towards', models.CharField(choices=[('INITIATOR', 'Initiator'), ('SUCCESSOR', 'Successor')], default='SUCCESSOR', max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='core.user')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiator', to='core.user')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='successor', to='core.user')),
            ],
        ),
    ]
