# Generated by Django 3.2.6 on 2021-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField()),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
