# Generated by Django 3.2.6 on 2021-09-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thenewbostonwallet'),
        ('escrow', '0002_tradeoffers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeOffers',
            new_name='TradeOffer',
        ),
    ]
