# Generated by Django 3.2.6 on 2021-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_alter_user_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
