# Generated by Django 3.2.6 on 2021-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_user_withdrawl_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='uuid_hex',
            field=models.CharField(default='jskldfllsdjfljldksjklfjkl', max_length=255),
            preserve_default=False,
        ),
    ]
