# Generated by Django 3.2.6 on 2021-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_escrow_uuid_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='uuid_hex',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
