# Generated by Django 3.2.6 on 2021-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_alter_escrow_uuid_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='initiator_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='successor_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
