# Generated by Django 3.2.6 on 2021-08-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0009_usertransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='settled_towards',
            field=models.CharField(choices=[('INITIATOR', 'Initiator'), ('SUCCESSOR', 'Successor')], default='SUCCESSOR', max_length=255),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute'), ('ADMIN_SETTLED', 'Admin Settled'), ('ADMIN_CANCELLED', 'Admin Cancelled')], max_length=255),
        ),
    ]
