# Generated by Django 3.2.6 on 2021-08-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0010_auto_20210827_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='escrow.user'),
        ),
    ]
