# Generated by Django 3.2.6 on 2021-08-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0011_alter_escrow_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
