# Generated by Django 3.2.6 on 2021-08-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0012_delete_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionhistory',
            name='transaction',
            field=models.ForeignKey(default='f8adf316-342f-4e46-8d63-df0845e531e7', on_delete=django.db.models.deletion.DO_NOTHING, to='escrow.transaction'),
            preserve_default=False,
        ),
    ]
