# Generated by Django 3.2.6 on 2021-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0013_usertransactionhistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
