# Generated by Django 3.2.6 on 2021-09-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_auto_20210916_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowuser',
            name='total_disputes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escrowuser',
            name='total_escrows',
            field=models.IntegerField(default=0),
        ),
    ]
