# Generated by Django 3.2.7 on 2021-11-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertransactionhistory_type'),
        ('escrow', '0003_auto_20210916_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscrowUser',
            new_name='Profile',
        ),
    ]
