# Generated by Django 3.2.7 on 2021-11-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_rename_escrowuser_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeOffer',
        ),
    ]
