# Generated by Django 3.2.7 on 2021-11-12 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertransactionhistory_type'),
        ('escrow', '0005_delete_tradeoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('amount', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
        ),
    ]
