# Generated by Django 3.2.7 on 2021-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='payment_method',
            field=models.CharField(default='NULL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
