# Generated by Django 3.2.7 on 2021-11-16 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211113_1617'),
        ('escrow', '0007_auto_20211113_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
