# Generated by Django 3.2.7 on 2021-11-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0008_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='payment_method',
        ),
    ]
