# Generated by Django 3.2.7 on 2021-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0010_auto_20211118_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='SELL', max_length=255),
            preserve_default=False,
        ),
    ]
