# Generated by Django 3.2.7 on 2022-01-31 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211113_1617'),
        ('escrow', '0012_escrow_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negative_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='neutral_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='positive_feeback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute'), ('ADMIN_SETTLED', 'Admin Settled'), ('ADMIN_CANCELLED', 'Admin Cancelled')], max_length=255),
        ),
        migrations.CreateModel(
            name='EscrowReview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('NEUTRAL', 'Neutral')], max_length=255)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escrow.escrow')),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
        ),
    ]
