# Generated by Django 3.2.6 on 2021-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='guild_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guild',
            name='total_fee_collected',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_fees_collected',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='thenewbostonwallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thenewbostonwallet',
            name='locked',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
